# Generated by Django 4.2.25 on 2025-11-12 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0008_boardpreference_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kanban.activity', verbose_name='Actividad')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Comentario de Actividad',
                'verbose_name_plural': 'Comentarios de Actividades',
                'ordering': ['created_at'],
            },
        ),
    ]
