# Generated by Django 4.2.25 on 2025-11-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0011_taskattachment_subtaskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Recordatorio enviado'),
        ),
    ]
