# Generated by Django 4.2.25 on 2025-10-31 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='kanban.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Subtarea',
                'verbose_name_plural': 'Subtareas',
                'ordering': ['order'],
            },
        ),
    ]
