# Generated by Django 4.2.25 on 2025-11-05 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('create_task', 'Crear Tarea'), ('edit_task', 'Editar Tarea'), ('delete_task', 'Eliminar/Cerrar Tarea'), ('move_task', 'Mover Tarea'), ('create_list', 'Crear Lista'), ('create_subtask', 'Crear Subtarea'), ('edit_subtask', 'Editar Subtarea'), ('toggle_subtask', 'Completar/Descompletar Subtarea'), ('delete_subtask', 'Eliminar Subtarea')], max_length=50, verbose_name='Tipo de Actividad')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='kanban.list', verbose_name='Lista')),
                ('subtask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='kanban.subtask', verbose_name='Subtarea')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='kanban.task', verbose_name='Tarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created_at'],
            },
        ),
    ]
