# Generated by Django 4.2.25 on 2025-11-07 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0005_list_created_by_subtask_created_by_task_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#4c1d95', max_length=20, verbose_name='Color del tablero')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_preference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Tablero',
                'verbose_name_plural': 'Preferencias de Tableros',
            },
        ),
    ]
