# Generated by Django 4.2.25 on 2025-11-07 01:26

from django.db import migrations, models
import kanban.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_boardpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(default=kanban.models.default_due_date, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=kanban.models.default_due_date, verbose_name='Fecha de vencimiento'),
        ),
    ]
