# Generated by Django 4.2.25 on 2025-11-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_subtask_due_date_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpreference',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='board_backgrounds/', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='boardpreference',
            name='color',
            field=models.CharField(default='transparent', max_length=20, verbose_name='Color del tablero'),
        ),
    ]
