# Generated by Django 4.2.25 on 2025-11-12 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0009_activitycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, max_length=32, verbose_name='Secreto TOTP')),
                ('enabled', models.BooleanField(default=False, verbose_name='2FA habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil 2FA',
                'verbose_name_plural': 'Perfiles 2FA',
            },
        ),
    ]
